name: Deploye Angular Application

on:
  push:
   branches:
     - main

jobs:
  build:
    runs-on: unbuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Login to docker hub
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
      - name: Build docker image
        run: docker build -t nithyanandnadar/printouthub .
      - name: Publish image to docker hun
        run: docker push nithyanandnadar/printouthub:latest
    
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from dockerhub
        run: docker pull nithyanandnadar/printouthub:latest
      - name: Delete old container
        run: docker rm -f angular-app-container
      - name: Run docker container
        run: docker container -d -p 4000:4200 --name angular-app-container nithyanandnadar/printouthub



